# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161313)
$foreground = rgb(E4E8EA)
$color0 = rgb(3E3B3A)
$color1 = rgb(40413C)
$color2 = rgb(45413D)
$color3 = rgb(646154)
$color4 = rgb(626264)
$color5 = rgb(6A6B6B)
$color6 = rgb(868E92)
$color7 = rgb(D0D5D8)
$color8 = rgb(929597)
$color9 = rgb(565751)
$color10 = rgb(5C5651)
$color11 = rgb(858170)
$color12 = rgb(838385)
$color13 = rgb(8E8E8F)
$color14 = rgb(B3BDC3)
$color15 = rgb(D0D5D8)
