# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(181820)
$foreground = rgb(FAF4E6)
$color0 = rgb(3F3E48)
$color1 = rgb(8C7F59)
$color2 = rgb(A98F75)
$color3 = rgb(A19692)
$color4 = rgb(839EAB)
$color5 = rgb(A89D8B)
$color6 = rgb(B4A889)
$color7 = rgb(EFE7D3)
$color8 = rgb(A7A193)
$color9 = rgb(BBAA77)
$color10 = rgb(E1BF9D)
$color11 = rgb(D7C8C3)
$color12 = rgb(AFD2E4)
$color13 = rgb(E0D1B9)
$color14 = rgb(F0DFB7)
$color15 = rgb(EFE7D3)
