# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(F9FAFC)
$foreground = rgb(131B20)
$color0 = rgb(FEFFFF)
$color1 = rgb(666A6F)
$color2 = rgb(726252)
$color3 = rgb(4F5E6C)
$color4 = rgb(525A61)
$color5 = rgb(26313B)
$color6 = rgb(202C36)
$color7 = rgb(131B20)
$color8 = rgb(71757A)
$color9 = rgb(888E94)
$color10 = rgb(98836E)
$color11 = rgb(6A7D90)
$color12 = rgb(6E7881)
$color13 = rgb(32424E)
$color14 = rgb(2B3B48)
$color15 = rgb(06090B)
