[FileDialog]
history=file:///run/media/timshel/HGST/qtorrent, file:///, file:///home/timshel, file:///home/timshel/Downloads
lastVisited=file:///home/timshel/Downloads/completed
qtVersion=6.8.1
shortcuts=file:, file:///home/timshel
sidebarWidth=46
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\xbd\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\x30\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\0\xbb\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=Detail
