# Schema
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Use the augmented arrow up command for the k key
[[mgr.prepend_keymap]]
on   = [ "k" ]
run  = "plugin augment-command 'arrow -1'"
desc = "Move cursor up"


# Use the augmented arrow down command for the j key
[[mgr.prepend_keymap]]
on   = [ "j" ]
run  = "plugin augment-command 'arrow 1'"
desc = "Move cursor down"


# Use K to move up in the parent directory
[[mgr.prepend_keymap]]
on   = [ "K" ]
run  = "plugin augment-command 'parent_arrow -1'"
desc = "Move cursor up in the parent directory"


# Use J to move down in the parent directory
[[mgr.prepend_keymap]]
on   = [ "J" ]
run  = "plugin augment-command 'parent_arrow 1'"
desc = "Move cursor down in the parent directory"


# Use Ctrl + k to seek 5 units up in the preview pane
[[mgr.prepend_keymap]]
on   = [ "<C-k>" ]
run  = "seek -5"
desc = "Seek up 5 units in the preview pane"


# Use Ctrl + j to seek 5 units down in the preview pane
[[mgr.prepend_keymap]]
on   = [ "<C-j>" ]
run  = "seek 5"
desc = "Seek down 5 units in the preview pane"

# Use the augmented enter command for the l key
[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = "plugin augment-command 'enter'"
desc = "Enter the child directory, or open the file"


# Use the augmented enter command for the <Enter> key
[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin augment-command 'enter'"
desc = "Enter the child directory, or open the file"


# Use the augmented enter command for the <S-Enter> key
[[mgr.prepend_keymap]]
on   = [ "<S-Enter>" ]
run  = "plugin augment-command 'enter --interactive'"
desc = "Enter the child directory, or open the file interactively"


# Use the augmented enter command for the <Right> key
# but without skipping directories
[[mgr.prepend_keymap]]
on   = [ "L" ]
run  = "plugin augment-command 'enter --no-skip'"
desc = "Enter the child directory, or open the file"


# Use the augmented leave command for the h key
[[mgr.prepend_keymap]]
on   = [ "h" ]
run  = "plugin augment-command 'leave'"
desc = "Go back to the parent directory"


# Use the augmented leave command for the <Left> key
# but without skipping directories
[[mgr.prepend_keymap]]
on   = [ "H" ]
run  = "plugin augment-command 'leave --no-skip'"
desc = "Go back to the parent directory"


# Use the augmented tab create command for the t key
[[mgr.prepend_keymap]]
on   = [ "t" ]
run  = "plugin augment-command 'tab_create --current'"
desc = "Create a new tab with CWD"


# Use d to cut files
[[mgr.prepend_keymap]]
on   = [ "d" ]
run  = "yank --cut"
desc = "Cut the selected files"


# Use the augmented paste command for the p key
# to paste files
[[mgr.prepend_keymap]]
on   = [ "p" ]
run  = "plugin augment-command 'paste'"
desc = "Paste the files"


# Use the augmented paste command for the P key
# to paste files and overwrite the destination file if it exists
[[mgr.prepend_keymap]]
on   = [ "P" ]
run  = "plugin augment-command 'paste --force'"
desc = "Paste the files (overwrite if the destination exists)"


# Use _ to create a new file or directory
[[mgr.prepend_keymap]]
on   = [ "_" ]
run  = "plugin augment-command 'create'"
desc = "Create a file or directory"


# Use + to create a new file or directory
[[mgr.prepend_keymap]]
on   = [ "+" ]
run  = "plugin augment-command 'create'"
desc = "Create a file or directory"


# Use x to move files to the trash
[[mgr.prepend_keymap]]
on   = [ "x" ]
run  = "plugin augment-command 'remove'"
desc = "Move the files to the trash"


# Use X to delete files permanently
[[mgr.prepend_keymap]]
on   = [ "X" ]
run  = "plugin augment-command 'remove --permanently'"
desc = "Permanently delete the files"


# Use Ctrl + s to open a shell in the current directory
[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"


# Use i to open files using the pager
[[mgr.prepend_keymap]]
on   = [ "i" ]
run  = "plugin augment-command 'pager'"
desc = "Open files with the default pager"


# Use r to rename files with the cursor before the file extension
[[mgr.prepend_keymap]]
on   = [ "r" ]
run  = "plugin augment-command 'rename --cursor=before_ext'"
desc = "Rename a file or directory"


# # Use R to remove the whole file name when renaming
# [[manager.prepend_keymap]]
# on   = [ "R" ]
# run  = "plugin augment-command 'rename --empty=all'"
# desc = "Rename file and remove the whole file name"
#

# Use I to rename files with the cursor at the start of the file name
[[mgr.prepend_keymap]]
on   = [ "I" ]
run  = "plugin augment-command 'rename --cursor=start'"
desc = "Rename file at the start of the file name"


# Use A to rename files with the cursor at the end of the file name
[[mgr.prepend_keymap]]
on   = [ "A" ]
run  = "plugin augment-command 'rename --cursor=end'"
desc = "Rename file with the cursor at the end of the file name"


# Use C to remove the whole file name when renaming
[[mgr.prepend_keymap]]
on   = [ "C" ]
run  = "plugin augment-command 'rename --empty=all'"
desc = "Rename file and remove the whole file name"

# Use cm to remove the file name when renaming
[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "rename --empty=stem --cursor=start"
desc = "Rename file and remove the file name"

# Use gc to go to the config directory
[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/.config"
desc = "Go to the config directory"


# Use gp to go to the projects directory
[[mgr.prepend_keymap]]
on   = [ "g", "g" ]
run = "tab_switch 1 --relative"
desc = "Switch to the next tab"


# Use gu to go to school directory
[[mgr.prepend_keymap]]
on   = [ "g", "f" ]
run = "tab_switch -1 --relative"
desc = "Switch to the previous tab"

# The relative motions plugin keymaps,
# which are just to use the number
# keys to move in relative steps
[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "["
run = "plugin whoosh jump_by_key"
desc = "Jump bookmark by key"

# Direct fuzzy search access
[[mgr.prepend_keymap]]
on = "}"
run = "plugin whoosh fuzzy"
desc = "Direct fuzzy search for bookmarks"

# Basic bookmark operations
[[mgr.prepend_keymap]]
on = [ "]", "a" ]
run = "plugin whoosh save"
desc = "Add bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "A" ]
run = "plugin whoosh save_cwd"
desc = "Add bookmark (current directory)"

# Temporary bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "t" ]
run = "plugin whoosh save_temp"
desc = "Add temporary bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "T" ]
run = "plugin whoosh save_cwd_temp"
desc = "Add temporary bookmark (current directory)"

# Jump to bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "f" ]
run = "plugin whoosh jump_by_fzf"
desc = "Jump bookmark by fzf"

# Delete bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "d" ]
run = "plugin whoosh delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "D" ]
run = "plugin whoosh delete_by_fzf"
desc = "Delete bookmarks by fzf (use TAB to select multiple)"

[[mgr.prepend_keymap]]
on = [ "]", "C" ]
run = "plugin whoosh delete_all"
desc = "Delete all user bookmarks"

# Rename bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "r" ]
run = "plugin whoosh rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "R" ]
run = "plugin whoosh rename_by_fzf"
desc = "Rename bookmark by fzf"
[[mgr.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = "o"
run  = "plugin open-with-cmd block"
desc = "Open with command in the terminal"

[[mgr.prepend_keymap]]
on   = "O"
run  = "plugin open-with-cmd"
desc = "Open with command"

# sudo cp/mv
[[mgr.prepend_keymap]]
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

#sudo cp/mv --force
[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste"

# sudo mv
[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

# sudo ln -s (absolute-path)
[[mgr.prepend_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

# sudo ln -s (relative-path)
[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

# sudo ln
[[mgr.prepend_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

# sudo touch/mkdir
[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

# sudo trash
[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

# sudo delete
[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"




