# Schema
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

# Configurations for the file manager
[mgr]

# Ratio for the panes in the file manager
# This follows the lf configuration
ratio = [1, 2, 3]

# Sort naturally
sort_by = "natural"

# Show directories first
sort_dir_first = true

# Show hidden files
show_hidden = true

# Set the scroll offset to 8 from the bottom and top
scrolloff = 8


# Configuration for the file previewer
[preview]
cache_dir = "~/.cache/yazi"
image_quality = 75
# Make the maximum size of the images larger
max_width = 3000
max_height = 3000


# Configuration for the openers
[opener]
emacs = [{ run = 'emacs -- "$@"', block = false, desc = "Open in Emacs" }]

analyse = [{ run = 'spek -- "$@"', block = false, desc = "Analyse spectrum" }]


# Configuration for the opener rules
[open]
prepend_rules = [
    { mime = "{audio,video}/*", use = [
        "play",
        "reveal",
        "analyse",
    ] },
    { name = "*.{org,tex,bib}", use = [
        "emacs",
        "edit",
        "reveal",
    ] },
]
    
[plugin]
  prepend_preloaders = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
  ]
  prepend_previewers = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'},
    { mime = "inode/directory", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'},
    { mime = "application/subrip", run = "mediainfo" },
  ]
