# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E5EBF3
background         #272925
cursor             #8A98AF

active_tab_foreground     #272925
active_tab_background     #E5EBF3
inactive_tab_foreground   #E5EBF3
inactive_tab_background   #272925

active_border_color   #E5EBF3
inactive_border_color #272925
bell_border_color     #233450

color0      #4D4F4A
color1		#233450
color2		#233450
color3		#4F5E76
color4		#647137
color5		#818FA1
color6		#8795A7
color7		#D1DAE6
color8		#9299A1
color9		#2F456B
color10		#2F456B
color11		#697E9D
color12		#859749
color13		#ACBFD7
color14		#B4C7DE
color15		#D1DAE6
