# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = fcitx5 &
exec-once = tixati &
exec-once = udiskie --tray &
exec-once = xdman-beta &
exec = gsettings set org.gnome.desktop.interface cursor-theme catppuccin-frappe-red-cursors
