# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this



bind = $mainMod, X, exec, noctalia msg panel-toggle session
bind = $mainMod, C, exec, $UserScripts/SwitchAudioSink.sh
bind = $mainMod, S, exec, kitty btop

bindl = $mainMod, Up, exec, noctalia msg volume-up
bindl = $mainMod, Down, exec, noctalia msg volume-down
bindl = $mainMod, Right, exec, noctalia msg volume-up 1
bindl = $mainMod, Left, exec, noctalia msg volume-down 1
bindld = $mainMod, Z, toggle mic mute, exec, noctalia msg volume-mute
bind = $mainMod, R, exec, chromium
