# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# FIXED: Changed from 'maximize' to 'fullscreen' using V2 syntax to ensure True Fullscreen
windowrule = fullscreen 0, workspace 2, match:class ^(zen)$

# windowrulev2 = fullscreen, class:^(kitty)$
windowrule = fullscreen on, match:class ^(org.wezfurlong.wezterm)$
windowrule = workspace 3, match:class ^(kitty)$
windowrule = workspace 9, match:class ^(xdm-app)$
# windowrulev2 = workspace 1, class:^(org.wezfurlong.wezterm)$
windowrule = workspace 1, match:class ^(foot)$
windowrule = workspace 4, match:class ^(com.mitchellh.ghostty)$
windowrule = workspace 5, match:class ^(mpv)$
windowrule = workspace 6, match:class ^(org.pwmt.zathura)$
windowrule = workspace 6, match:class ^(chromium)$
windowrule = workspace 7, match:class ^(vimiv)$
windowrule = workspace 7, match:class ^(swayimg)$
windowrule = workspace 8, match:class ^(tixati)$

windowrule = opacity 0.7 0.7,match:class ^(com.mitchellh.ghostty)$
# FIXED: Removed [float]. Floating windows that are forced into fullscreen often 
# conflict with Wayland layer shells. Let it tile, then fullscreen it.
workspace = 2, on-created-empty:zen-browser
