### Profile ###

include="~~/profiles.conf"

### Video ###
volume-max=200
volume=140
cache=yes
demuxer-readahead-secs=60
demuxer-seekable-cache=yes
demuxer-max-bytes=1000MiB
video-reversal-buffer=500MiB
audio-reversal-buffer=200MiB
demuxer-max-back-bytes=700MiB
hwdec-extra-frames=256
#demuxer-cache-wait=yes
sub-font='Noto Sans S Chinese Regular'
slang=ja,jp,jpn,jap,Japanese,en,eng,English,en,eng,English
alang=ja,jp,jpn,jap,Japanese,en,eng,English
sub-blur=0.5
sub-font-size=36
sub-color="#FFFFFFFF"
sub-border-color="#FF262626"
sub-border-size=1.5
sub-shadow-offset=1
sub-shadow-color="#33000000"
sub-spacing=0.5
sub-ass-override=force
blend-subtitles

vo=gpu-next
gpu-api=vulkan
hwdec=vulkan
# priority=high 
gpu-context=waylandvk
#hwdec=d3d12va-copy
profile=high-quality   
#d3d11-adapter=NVIDIA  

# hwdec=auto-safe
# vo=gpu-next
# hwdec=auto-copy
# hwdec-codecs=all
#
deband=no
deband-iterations=1
deband-threshold=48
deband-range=16
deband-grain=32

temporal-dither=yes

### Audio and Subtitles ###

# sid=1
sub-auto=fuzzy
sub-fix-timing=yes
audio-channels=auto  
blend-subtitles=yes
sub-ass-override=yes  
audio-file-auto=fuzzy 
audio-pitch-correction=yes
audio-normalize-downmix=yes              
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes
# sub-file-paths=sub;subs;subtitles;Subs
sub-file-paths=**
af=lavfi=[dynaudnorm=g=3:f=250:r=0.9:p=0.9:m=10]

## Audio Filters to Test ##

#lavfi=[loudnorm=i=-10]
#lavfi=[loudnorm=i=-20]
#af=speechnorm=e=4:p=0.4
#af='lavfi=[dynaudnorm=f=200:g=5:r=0.1]'
#af=lavfi=[loudnorm=I=-16:TP=-2:LRA=11]

# boost speech volume
#af=@normalize:speechnorm=e=10:r=0.0005:l=1
# loudnorm works well too, but uses more CPU
#af=@normalize:loudnorm=I=-10

#af-toggle=@loudnorm:lavfi=[loudnorm=I=-16:TP=-3:LRA=4]
#af-toggle=@dynaudnorm:lavfi=[dynaudnorm=g=5:f=250:r=0.9:p=0.5]

#af-toggle=@loudnorm:!loudnorm=I=-25:TP=-1.5:LRA=1:linear=false
#af-toggle=@dynaudnorm:!dynaudnorm=f=500:g=17:r=0.1
#af-toggle=format:srate=48000

### General ###

osc=no
fs=yes
snap-window
save-position-on-quit=yes
watch-later-dir="~~/cache/watch_later"

### OSD ###

border=no
osd-bar=no
osd-bold=yes
osd-font-size=37
osd-font='JetBrains Mono'
