# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = tile,^(Brave-browser)$
windowrule = tile,^(Chromium)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float,^(qalculate-gtk)$
windowrulev2 = fullscreen, class:^(waterfox)$
windowrulev2 = fullscreen, class:^(kitty)$
windowrulev2 = fullscreen, class:^(Alacritty)$
windowrulev2 = workspace 2, class:^(waterfox)$
windowrulev2 = workspace 9, class:^(xdm-app)$
windowrulev2 = workspace 1, class:^(kitty)$
windowrulev2 = workspace 4, class:^(Alacritty)$
windowrulev2 = workspace 5, class:^(geany)$
windowrulev2 = workspace 6, class:^(org.pwmt.zathura)$
windowrulev2 = workspace 8, class:^(org.qbittorrent.qBittorrent)$

